/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bc307ea92519f305b278e0467d64221b)
interface __BaseEnv_Env {
	SCHEDULE_CACHE: KVNamespace;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
